### PR TITLE
Fix to test and webpack version upgrade

### PR DESCRIPTION
**Pull request by eugenioclrc**
I have found some errors in the test file _test/network.js_

`assert.isBelow(0.9, lstm.activate([0]), 'LSTM error');`

**lstm.activate([0])** returns arrays of numbers, but assert.isBelow expects a number, so this is how it should be;

`assert.isBelow(0.9, lstm.activate([0])[0], 'LSTM error');`

Also i have upgrade webpack and configure babel to work in a ES6 sintax

### CODE REVIEW

**Comment by wagenaartje** [comment]
Hi! Thanks for the pull request. I did not notice the errors in the assertions during the Travis testing. Thanks for fixing that.

**About Babel:** Neataptic is micro-optimized to the fullest, e.g. changing a single `var` to `let` could reduce training time by a factor of 2. _That is reason one why I don't think Babel is a good idea_. It could possibly kill performance of the library.

But ECMAScript 6 is [almost fully supported](https://kangax.github.io/compat-table/es6/) by all major browsers and supported Node versions. What i'm saying is: there is no need for Babel (right now), and if your browser or runtime doesn't support Neataptic, then it is up to you to change your project environment.

If there is any specific reason why you want to include Babel, please let me know.

**Comment by eugenioclrc** [comment]
You are totally right, there is no need to use babel.

**Comment by wagenaartje** [comment]
Hi, I see you removed babel again. I'm testing your commits and i'm getting this error:

```js
ERROR in Entry module not found: Error: Can't resolve 'babel-loader' in '/home/travis/build/wagenaartje/neataptic'
```

**Comment by eugenioclrc** [comment]
I forget to remove babel from the webpack config.

**Comment by wagenaartje** [comment]
What does `new webpack.optimize.ModuleConcatenationPlugin(),` do?

**Comment by eugenioclrc** [comment]
From https://webpack.js.org/plugins/module-concatenation-plugin/

In the past, one of webpack’s trade-offs when bundling was that each module
in your bundle would be wrapped in individual function closures. These
wrapper functions made it slower for your JavaScript to execute in the
browser. In comparison, tools like Closure Compiler and RollupJS ‘hoist’ or
concatenate the scope of all your modules into one closure and allow for
your code to have a faster execution time in the browser.

**Comment by wagenaartje** [comment]
Any idea why it's throwing the following error on me upon building;

```js
    new webpack.optimize.ModuleConcatenationPlugin(),
    ^

TypeError: webpack.optimize.ModuleConcatenationPlugin is not a constructor
    at Object.<anonymous> (C:\Users\20173591\Documents\GitHub\neataptic\webpack.config.js:37:5)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at requireConfig (C:\Users\20173591\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:97:18)
    at C:\Users\20173591\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\20173591\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:102:15)
    at yargs.parse (C:\Users\20173591\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:171:41)
    at Object.Yargs.self.parse (C:\Users\20173591\AppData\Roaming\npm\node_modules\webpack\node_modules\yargs\yargs.js:533:18)
    at Object.<anonymous> (C:\Users\20173591\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:152:7)
```

**Comment by eugenioclrc** [comment]
Yeha, have you update webpack to webpack2? Run 'npm i' after pull so your
packages upgrade.

**Pull request merged**
