### PR TITLE
Multithreading

### PR DESCRIPTION
**Pull request by wagenaartje**
Multithreading introduced for the `Network.evolve` function. Also drastically improved the crossover operation for larger networks.

Multithreading for backpropagation coming soon. This will only work for layered networks.

If multithreading has been done, i'll start looking into using the GPU.

### CODE REVIEW

**Comment by wagenaartje** [comment]
I'm leaving this PR here for 3 days for comments. I will then merge.

Multithreading for node.js and multithreading for other functions inside Neataptic will be supported in later versions, they shall be introduced soon.

**Comment by dsdenes** [comment]
Hi, is somebody currently working on Node.js multithreading? I would be happy to implement it.

**Comment by wagenaartje** [comment]
At this moment, I am not aware of anyone working on a Node.js multithreading inplementation; feel free to make an implementation. 

In the Network.evolve() function you can find the generic interface that is used to evaluate networks with multithreading. Try to see if you could integrate it nicely with that.

If you have any questions during the development process, please let me know :smile:.

**Comment by tracycollins** [comment]
This is a great idea! I've been playing with the module, and evolve times get quite long for larger networks.

If I were a better at js and node, I would help. But I'm still taking baby steps. Thanks!

**Pull request merged**
